version: 2.1
executors:
  build-and-test-executor:
    docker:
      - image: circleci/node:12.6.3
jobs:
  build-and-test:
    executor:
      name: build-and-test-executor
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
