version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
  codecov: codecov/codecov@1.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
            - run: npm test
            - codecov/upload:
                file: { { client/coverage } }
            - codecov/upload:
                file: { { server/coverage } }
  upload-coverage:
    execution:
      name: node/default
    steps:
      -checkout
      -node/with-cache:
        steps:
          - codecov/upload:
              file: { { client/coverage } }
          - codecov/upload:
              file: { { server/coverage } }
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
